### ISSUE TITLE
Bug 1920 이하의 화면에선 가로와 세로 스크롤이 보임

### ISSUE THREAD

**Issue by qetqet910** [alittlekitten/SsocoTimer#64]
body에 overflow: hidden 해줘용

**Comment by alittlekitten** [comment]
![image](https://user-images.githubusercontent.com/14370441/166173549-ca6e4bee-5f4d-45cd-b1a3-f5a6b0aafdc4.png)
감사합니다 :) 바로 반영하겠습니다!
